config = {
'expname': 'self_hybrid_f16_g12',
'logdir': './logs/Amily',
'device': 'cuda:0',
'data_downsample': 1,
'data_dirs': ['./plenoxels/data/self/Amily_train'],
'contract': False,
'ndc': False,
'isg': False,
'isg_step': -1,
'ist_step': -1,
'keyframes': False,
'scene_bbox': [[-1.3, -1.3, -1.3], [1.3, 1.3, 1.3]],
'num_steps': 150000,
'batch_size': 4096,
'scheduler_type': 'warmup_cosine',
'optim_type': 'adam',
'lr': 0.002,
'distortion_loss_weight': 0.001,
'histogram_loss_weight': 1.0,
'l1_time_planes': 0.0001,
'l1_time_planes_proposal_net': 0.0001,
'plane_tv_weight': 0.0001,
'plane_tv_weight_proposal_net': 0.0001,
'time_smoothness_weight': 0.001,
'time_smoothness_weight_proposal_net': 0.001,
'save_every': 10000,
'valid_every': 160000,
'save_outputs': True,
'train_fp16': True,
'single_jitter': False,
'num_samples': 48,
'num_proposal_samples': [256, 128],
'num_proposal_iterations': 2,
'use_same_proposal_network': False,
'use_proposal_weight_anneal': True,
'proposal_net_args_list': [{'num_input_coords': 4, 'num_output_coords': 8, 'resolution': [64, 64, 64, 30]}, {'num_input_coords': 4, 'num_output_coords': 8, 'resolution': [128, 128, 128, 30]}],
'concat_features_across_scales': True,
'density_activation': 'trunc_exp',
'linear_decoder': False,
'multiscale_res': [1, 2],
'grid_config': [{'grid_dimensions': 2, 'input_coordinate_dim': 4, 'output_coordinate_dim': 16, 'resolution': [64, 64, 64, 30]}],
}
